spring:
  application:
    name: recipeAndCart
  profiles:
    active:
      - api

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
recipe:
  base-url: https://openapi.foodsafetykorea.go.kr/api/
  req-type: /COOKRCP01/json/1/1000