spring:
  application:
    name: recipeAndCart
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - api

  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
recipe:
  base-url: https://openapi.foodsafetykorea.go.kr/api/
  req-type: /COOKRCP01/json/